spring:
  profiles:
    active: postgres
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}

---
spring:
  profiles: postgres
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/db
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379

